//go:build embed_frontend

// Package api: this file ships the SvelteKit static build inside the binary.
// Compiled in only when the build tag `embed_frontend` is set, which means
// `make build-release` does the embed and `make build` does not.
//
// The frontend is built as a SPA (adapter-static), so the layout is:
//
//	frontend/build/
//	  index.html
//	  _app/...    static JS/CSS chunks
//	  favicon.png
//	  ...
//
// Routes are client-side, so any unknown path under "/" must serve
// index.html — the SvelteKit router takes over. /api/v1/* and /healthz are
// already registered before this fallback runs, so they are never
// shadowed.

package api

import (
	"embed"
	"io"
	"io/fs"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// frontendFS holds the contents of frontend/build/. Generated by
// `npm run build` in the frontend/ directory before compiling with
// `-tags embed_frontend`.
//
//go:embed all:frontend_build
var frontendFS embed.FS

func registerFrontend(r chi.Router) {
	sub, err := fs.Sub(frontendFS, "frontend_build")
	if err != nil {
		// If embedding succeeded, this Sub call cannot fail. Panic at
		// register time rather than serving 500s for every request.
		panic("frontend embed broken: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(sub))

	r.Get("/*", func(w http.ResponseWriter, req *http.Request) {
		// Don't shadow API routes; chi has already routed those to their
		// handlers, so reaching here means the path is for the SPA.
		if strings.HasPrefix(req.URL.Path, "/api/") || req.URL.Path == "/healthz" {
			http.NotFound(w, req)
			return
		}
		// Try the file as-is. If it exists, serve it (with the right
		// content-type and caching). If it doesn't, fall back to
		// index.html so the SvelteKit router can handle the route.
		if exists(sub, req.URL.Path) {
			fileServer.ServeHTTP(w, req)
			return
		}
		serveIndex(w, sub)
	})
}

func exists(fsys fs.FS, p string) bool {
	p = strings.TrimPrefix(p, "/")
	if p == "" {
		return true // index.html
	}
	f, err := fsys.Open(p)
	if err != nil {
		return false
	}
	_ = f.Close()
	return true
}

func serveIndex(w http.ResponseWriter, fsys fs.FS) {
	f, err := fsys.Open("index.html")
	if err != nil {
		http.Error(w, "frontend missing", http.StatusInternalServerError)
		return
	}
	defer f.Close()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = io.Copy(w, f)
}
